// auth actions
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

// post actions
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_ERROR = "POST_ERROR";

// follow actions
export const FOLLOWING_SUCCESS = "FOLLOWING_SUCCESS";
export const FOLLOWING_ERROR = "FOLLOWING_ERROR";

// interact actions
export const LOVE = "LOVE";
export const COMMENT = "COMMENT";

export const RETRIEVE_POSTS = "RETRIEVE_POSTS";

export const PUBLIC_KEY = 'GA6GMNHXZ332WAYNW3Q2AJ7YKE5WFYCTOAFJLNEFARHKWTMT7HQR2ZIK';
export const SECRET_KEY = 'SC3PILQTZKA7EYDVUV5VV2LEV4TI4O7DVLR5F7JG3JVENBEBHMLUXMP2';

export const ME_PUBLIC_KEY = 'SACS76RXDMK3VU3VOH4O66BCJZEZCJSMRRQCKPR3ULEULNEDN6PDJYLE';
export const ME_SECRET_KEY = 'GB3QYLBOOXGIWQ67WWJJSWCBLH46KM46M37BLHJX7HIPNBBKZH6R4OMV';
